version: "2.2"

services:
  cloud:
    container_name: cloud
    build: ./dockerfiles/nextcloud/  
    labels:
      - "traefik.frontend.rule=Host:cloud.${DOMAIN_NAME}"
      - "traefik.port=80"
      - "traefik.enable=true"
    links:
      - cloud_db:cloud_db
    volumes:
      - cloud_data:/var/www/html
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_HOST=cloud_db
      - NEXTCLOUD_ADMIN_USER=${ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASS}
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost cloud.${DOMAIN_NAME}
      - WOPI_URL=office.${DOMAIN_NAME}
    restart: always
    networks:
      - docker_default

  cloud_db:
    container_name: cloud_db
    image: postgres:latest
    restart: always
    volumes:
      - cloud_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    networks:
      - docker_default

  cloud_collabora:
    container_name: cloud_collabora
    build: ./dockerfiles/collabora/
    cap_add:
      - MKNOD
    environment:
      - domain=cloud\.${DOTS_ESCAPED_DOMAIN_NAME}
      - username=collabora_admin_username
      - password=collabora_admin_password
    restart: always
    networks:
      - docker_default


  cloud_collabora_nginx:
    container_name: cloud_collabora_nginx
    build: 
      context: ./dockerfiles/nginx/
      args:
        - domain_name=${DOMAIN_NAME}
    restart: always
    labels:
      - "traefik.frontend.rule=Host:office.${DOMAIN_NAME}"
      - "traefik.port=80"
      - "traefik.enable=true"
    links:
      - cloud_collabora:cloud_collabora
    networks:
      - docker_default
networks:
    docker_default:
      external:
        name: docker_default
volumes:
    cloud_data:
    cloud_db_data:
