version: "2.2"

services:
  cloud:
    container_name: cloud
    image: cloud:15.0   
    labels:
      - "traefik.frontend.rule=Host:cloud.domain_name"
      - "traefik.port=80"
      - "traefik.enable=true"
    links:
      - cloud_db:cloud_db
    volumes:
      - /DATA/docker/cloud/cloud_data:/var/www/html
    restart: always
    networks:
      - docker_default

  cloud_db:
    container_name: cloud_db
    image: postgres:latest
    restart: always
    volumes:
      - /DATA/docker/cloud/cloud_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=potgres_db
      - NEXTCLOUD_ADMIN_USER=admin_user
      - NEXTCLOUD_ADMIN_PASSWORD=admin_password
    networks:
      - docker_default

  cloud_collabora:
    container_name: cloud_collabora
    image: collabora:6.0
    cap_add:
      - MKNOD
    environment:
      - domain=cloud.domain_name
      - username=collabora_admin_username
      - password=collabora_admin_password
    restart: always
    networks:
      - docker_default

  cloud_collabora_nginx:
    container_name: cloud_collabora_nginx
    build: 
      context: ./dockerfiles/nginx/
      args:
        - domain_name=domain_name

    restart: always
    labels:
      - "traefik.frontend.rule=Host:office.domain_name"
      - "traefik.port=80"
      - "traefik.enable=true"
    links:
      - cloud_collabora:cloud_collabora
    networks:
      - docker_default
networks:
    docker_default:
      external:
        name: docker_default