version: "2.2"

services:
  cloud:
    container_name: cloud
    image: registry.picasoft.net/nextcloud:15.0   
    labels:
      - "traefik.frontend.rule=Host:cloud.domain_name"
      - "traefik.port=80"
      - "traefik.enable=true"
    links:
      - cloud_db:cloud_db
    volumes:
      - /DATA/docker/cloud/cloud_data:/var/www/html
    restart: always


  cloud_db:
    container_name: cloud_db
    image: postgres:9.6
    restart: always
    volumes:
      - /DATA/docker/cloud/cloud_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=potgres_db
      - NEXTCLOUD_ADMIN_USER=admin_user
      - NEXTCLOUD_ADMIN_PASSWORD=admin_password

  cloud_collabora:
    container_name: cloud_collabora
    image: registry.picasoft.net/collabora:6.0
    cap_add:
      - MKNOD
    environment:
      - domain=cloud.domain_name
      - username=collabora_admin_username
      - password=collabora_admin_password
    restart: always

  cloud_nginx:
    container_name: cloud_collabora_nginx
    image: registry.picasoft.net/pica-nginx:latest
    restart: always
    labels:
      - "traefik.frontend.rule=Host:office.domain_name"
      - "traefik.port=80"
      - "traefik.enable=true"
    links:
      - cloud_collabora:cloud_collabora
    volumes:
      - /DATA/docker/cloud/collabora_nginx_conf/default:/etc/nginx/sites-available/default
      - /DATA/docker/cloud/collabora_nginx_conf/nginx.conf:/etc/nginx/nginx.conf

